version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network

  # PHP-FPM Service
  php:
    image: php:8.2-fpm-alpine
    container_name: my-php
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: my-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # <-- Reads from .env
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: my-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mariadb"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" # <-- Reads from .env
    depends_on:
      - mariadb
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  db-data:
    driver: local
